#############################################################################
# Makefile for building: main
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Dec 16 19:49:06 2022
# Project:  project.pro
# Template: app
# Command: /nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/qmake -o Makefile project.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/linux-g++ -I. -I/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/include/QtCore -I/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/include/QtGui -I/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/lib
LIBS          = $(SUBLIBS)  -L/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/lib -lQtGui -L/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/lib -L/var/empty/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/AddComp.cpp \
		src/AddPop.cpp \
		src/Composition.cpp \
		src/FirstWindow.cpp \
		src/main.cpp \
		src/Playlist.cpp \
		src/Popurry.cpp \
		src/ViewWindow.cpp moc_AddComp.cpp \
		moc_AddPop.cpp \
		moc_FirstWindow.cpp \
		moc_ViewWindow.cpp
OBJECTS       = AddComp.o \
		AddPop.o \
		Composition.o \
		FirstWindow.o \
		main.o \
		Playlist.o \
		Popurry.o \
		ViewWindow.o \
		moc_AddComp.o \
		moc_AddPop.o \
		moc_FirstWindow.o \
		moc_ViewWindow.o
DIST          = /nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/unix.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/linux.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/gcc-base.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/g++-base.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/g++-unix.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/qconfig.pri \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt_functions.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt_config.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/default_pre.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/release.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/default_post.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/warn_on.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/unix/thread.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/moc.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/shared.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/resources.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/uic.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/yacc.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/lex.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/include_source_dir.prf \
		project.pro
QMAKE_TARGET  = main
DESTDIR       = 
TARGET        = main

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_AddComp.h ui_AddPop.h ui_FirstWindow.h ui_ViewWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project.pro  /nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/linux-g++/qmake.conf /nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/unix.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/linux.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/gcc-base.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/g++-base.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/g++-unix.conf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/qconfig.pri \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt_functions.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt_config.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/default_pre.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/release.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/default_post.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/warn_on.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/unix/thread.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/moc.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/shared.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/resources.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/uic.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/yacc.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/lex.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/include_source_dir.prf \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/lib/libQtGui.prl \
		/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/lib/libQtCore.prl
	$(QMAKE) -o Makefile project.pro
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/unix.conf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/linux.conf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/gcc-base.conf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/gcc-base-unix.conf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/g++-base.conf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/common/g++-unix.conf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/qconfig.pri:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt_functions.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt_config.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/exclusive_builds.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/default_pre.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/release.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/default_post.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/warn_on.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/qt.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/unix/thread.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/moc.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/shared.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/resources.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/uic.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/yacc.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/lex.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/share/qt-4.8.7/mkspecs/features/include_source_dir.prf:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/lib/libQtGui.prl:
/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/main1.0.0 || $(MKDIR) .tmp/main1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/main1.0.0/ && $(COPY_FILE) --parents src/AddComp.h src/AddPop.h src/Composition.h src/FirstWindow.h src/Playlist.h src/Popurry.h src/ViewWindow.h .tmp/main1.0.0/ && $(COPY_FILE) --parents src/AddComp.cpp src/AddPop.cpp src/Composition.cpp src/FirstWindow.cpp src/main.cpp src/Playlist.cpp src/Popurry.cpp src/ViewWindow.cpp .tmp/main1.0.0/ && $(COPY_FILE) --parents src/AddComp.ui src/AddPop.ui src/FirstWindow.ui src/ViewWindow.ui .tmp/main1.0.0/ && (cd `dirname .tmp/main1.0.0` && $(TAR) main1.0.0.tar main1.0.0 && $(COMPRESS) main1.0.0.tar) && $(MOVE) `dirname .tmp/main1.0.0`/main1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/main1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_AddComp.cpp moc_AddPop.cpp moc_FirstWindow.cpp moc_ViewWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AddComp.cpp moc_AddPop.cpp moc_FirstWindow.cpp moc_ViewWindow.cpp
moc_AddComp.cpp: src/AddComp.h
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/AddComp.h -o moc_AddComp.cpp

moc_AddPop.cpp: src/AddPop.h
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/AddPop.h -o moc_AddPop.cpp

moc_FirstWindow.cpp: src/Playlist.h \
		src/Composition.h \
		src/Popurry.h \
		src/FirstWindow.h
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/FirstWindow.h -o moc_FirstWindow.cpp

moc_ViewWindow.cpp: src/Playlist.h \
		src/Composition.h \
		src/Popurry.h \
		src/ViewWindow.h
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/ViewWindow.h -o moc_ViewWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_AddComp.h ui_AddPop.h ui_FirstWindow.h ui_ViewWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_AddComp.h ui_AddPop.h ui_FirstWindow.h ui_ViewWindow.h
ui_AddComp.h: src/AddComp.ui
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/uic src/AddComp.ui -o ui_AddComp.h

ui_AddPop.h: src/AddPop.ui
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/uic src/AddPop.ui -o ui_AddPop.h

ui_FirstWindow.h: src/FirstWindow.ui
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/uic src/FirstWindow.ui -o ui_FirstWindow.h

ui_ViewWindow.h: src/ViewWindow.ui
	/nix/store/9n90zzy8lf20raf0ww512fsbrwi22y0i-qt-4.8.7/bin/uic src/ViewWindow.ui -o ui_ViewWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

AddComp.o: src/AddComp.cpp src/AddComp.h \
		ui_AddComp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddComp.o src/AddComp.cpp

AddPop.o: src/AddPop.cpp src/AddPop.h \
		ui_AddPop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddPop.o src/AddPop.cpp

Composition.o: src/Composition.cpp src/Composition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Composition.o src/Composition.cpp

FirstWindow.o: src/FirstWindow.cpp src/AddComp.h \
		src/AddPop.h \
		src/FirstWindow.h \
		src/Playlist.h \
		src/Composition.h \
		src/Popurry.h \
		src/ViewWindow.h \
		ui_FirstWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FirstWindow.o src/FirstWindow.cpp

main.o: src/main.cpp src/Composition.h \
		src/Playlist.h \
		src/Popurry.h \
		src/FirstWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Playlist.o: src/Playlist.cpp src/Playlist.h \
		src/Composition.h \
		src/Popurry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Playlist.o src/Playlist.cpp

Popurry.o: src/Popurry.cpp src/Popurry.h \
		src/Composition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Popurry.o src/Popurry.cpp

ViewWindow.o: src/ViewWindow.cpp src/Playlist.h \
		src/Composition.h \
		src/Popurry.h \
		ui_ViewWindow.h \
		src/ViewWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ViewWindow.o src/ViewWindow.cpp

moc_AddComp.o: moc_AddComp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddComp.o moc_AddComp.cpp

moc_AddPop.o: moc_AddPop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddPop.o moc_AddPop.cpp

moc_FirstWindow.o: moc_FirstWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FirstWindow.o moc_FirstWindow.cpp

moc_ViewWindow.o: moc_ViewWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ViewWindow.o moc_ViewWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

